import Head from "next/head";
import { LoginComponent } from "../components/login";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Binar Mock Up Test | Front End</title>
        <meta name="description" content="Generated by Andri A" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoginComponent />
    </div>
  );
};

export default Home;
